feat: update pandas to 2.1.4+dfsg-8

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -3,7 +3,6 @@
 
 export DEB_BUILD_MAINT_OPTIONS = hardening=+all
 DPKG_EXPORT_BUILDFLAGS = 1
-export DEB_BUILD_OPTIONS = nocheck
 include /usr/share/dpkg/buildflags.mk
 include /usr/share/dpkg/pkg-info.mk
 
@@ -23,13 +22,23 @@ ifeq ($(DEB_HOST_ARCH),$(filter $(DEB_HOST_ARCH), amd64 i386 kfreebsd-amd64 kfre
 else
 	PYTEST_MARKER := not network and not slow
 endif
+ifeq (,$(findstring mips,$(DEB_HOST_ARCH))$(findstring hppa,$(DEB_HOST_ARCH))$(findstring _ia64_,_$(DEB_HOST_ARCH)_))
+	PYTEST_WARN_IGNORE :=
+else
+	# mips/hppa may have unusual NaN behaviour
+	# https://en.wikipedia.org/wiki/NaN#Encoding
+	# ia64 warns in test_groupby_quantile_all_na_group_masked (see 2.0.3+dfsg-6 build log)
+	PYTEST_WARN_IGNORE := -W "ignore:invalid value encountered:RuntimeWarning"
+endif
+
 # for matplotlib etc
 export HOME=$(CURDIR)/buildtmp
 
 # Split up the test suite to avoid running out of memory, use xvfb for plot tests, run but ignore potentially crashing tests; test_register_entrypoint expects an installed package, test_wrong_url needs internet, test_statsmodels is a circular dependency when adding a new Python version
 # The echo-random-characters is to allow searching for fails that don't show the usual test failure message i.e. crashes/errors
 # -v makes the log too long for salsa-ci
-export PYBUILD_TEST_ARGS=TEST_SUCCESS=true; cd {build_dir} ; for TEST_SUBSET in {build_dir}/pandas/tests/* ; do PANDAS_CI=1 LOCALE_OVERRIDE=C xvfb-run -a -s "-screen 0 1280x1024x24 -noreset" {interpreter} -m pytest -s -m "$(PYTEST_MARKER)" -k "not test_register_entrypoint and not test_wrong_url and not test_statsmodels" --confcutdir={build_dir}/pandas --deb-data-root-dir={dir}/pandas/tests --strict-data-files $$TEST_SUBSET || test $$? = 5 || TEST_SUCCESS=false && echo "rdjoqkol test state = $$TEST_SUCCESS"; done ; PANDAS_CI=1 LOCALE_OVERRIDE=C {interpreter} -m pytest -s -m "$(PYTEST_MARKER)" --forked --runxfail --confcutdir={build_dir}/pandas --deb-data-root-dir={dir}/pandas/tests --strict-data-files {build_dir}/pandas/tests/groupby/test_numba.py {build_dir}/pandas/tests/groupby/test_timegrouper.py {build_dir}/pandas/tests/groupby/transform/test_numba.py {build_dir}/pandas/tests/groupby/aggregate/test_numba.py {build_dir}/pandas/tests/window/test_numba.py {build_dir}/pandas/tests/window/test_apply.py {build_dir}/pandas/tests/window/test_online.py {build_dir}/pandas/tests/window/moments/test_moments_consistency_expanding.py || true ; rm -rf test-data.xml .pytest_cache ; $$TEST_SUCCESS
+# the grep -q is because trying to test __pycache__ is an error in pytest 8+, #1063959
+export PYBUILD_TEST_ARGS=TEST_SUCCESS=true; cd {build_dir} ; for TEST_SUBSET in {build_dir}/pandas/tests/* ; do echo $$TEST_SUBSET | grep -q -e __pycache__ || PANDAS_CI=1 LC_ALL=C.UTF-8 xvfb-run -a -s "-screen 0 1280x1024x24 -noreset" {interpreter} -m pytest -s -m "$(PYTEST_MARKER)" $(PYTEST_WARN_IGNORE) -k "not test_register_entrypoint and not test_wrong_url and not test_statsmodels" --confcutdir={build_dir}/pandas --deb-data-root-dir={dir}/pandas/tests $$TEST_SUBSET || test $$? = 5 || TEST_SUCCESS=false && echo "rdjoqkol test state = $$TEST_SUCCESS"; done ; rm -rf test-data.xml .pytest_cache ; $$TEST_SUCCESS
 
 export PYBUILD_EXT_DESTDIR=debian/python3-pandas-lib
 export PYBUILD_DESTDIR=debian/python3-pandas
@@ -53,7 +62,7 @@ export SHELL=/bin/bash
 # To upgrade to a new upstream version, this process must be repeated
 # Warning - has not been tested for some time
 _cythonize%: override_dh_clean # force removal of previous copies
-	python$(*:2=) setup.py cythonDEB_BUILD_OPTIONS
+	python$(*:2=) setup.py cython
 	D=debian/cythonized-files$(*:2=) && \
 		git rm -rf $$D || rm -rf $$D; \
 		find pandas/ -regex '.*\.c\(\|pp\)' | while read f; do \
@@ -76,7 +85,9 @@ cythonize: _cythonize3
 
 override_dh_clean:
 	find pandas/ -regex '.*\.c\(\|pp\)' | xargs grep -l -e 'Generated by Cython'  | xargs -r rm -f
-	rm -rf build buildtmp doc/build *-stamp # pandas.egg-info pandas/datasets/__config__.py
+	# the || true is because this will fail without docutils (-arch or nodoc builds)
+	cd doc && LC_ALL=C.UTF-8 python3 make.py clean || true
+	rm -rf build buildtmp *-stamp doc/source/savefig doc/source/user_guide/styled.xlsx doc/source/index.rst
 	dh_clean
 
 override_dh_auto_build-arch: # ${PY3VERS:%=_uncythonize%}
@@ -88,11 +99,12 @@ override_dh_auto_build-arch: # ${PY3VERS:%=_uncythonize%}
 override_dh_auto_build-indep: override_dh_auto_build-arch
 ifeq (,$(filter nodoc,$(DEB_BUILD_OPTIONS)))
 	: # Build Documentation
-	cd doc && PYTHONPATH=$(CURDIR)/.pybuild/cpython3_$(PY3VER)/build LC_ALL=C python3 make.py html
-	# strip build paths and statsmodels timestamps for reproducibility, and online Javascript for privacy
+	cd doc && PYTHONPATH=$(CURDIR)/.pybuild/cpython3_$(PY3VER)/build LC_ALL=C.UTF-8 LANGUAGE=C.UTF-8 python3 make.py html
+	# strip build paths, object IDs and statsmodels timestamps for reproducibility, and online Javascript for privacy
 	for html in `find doc/build/html -name _modules -prune -o -name "*.html" -o -name "*.ipynb"` ; do \
 	    sed -i -e 's#$(CURDIR)/.pybuild/[^/]*/build/pandas/#/usr/lib/python3/dist-packages/pandas/#g' \
 	    -e 's#$(CURDIR)/debian/python3-pandas/usr/lib/python3/dist-packages/pandas/#/usr/lib/python3/dist-packages/pandas/#g' \
+	    -e 's# at 0x[0-9a-f]\{8,16\}\(&gt;\|>\)# at 0xadde5de1e8ed\1#g' \
 	    -e 's#\(Date:.*\)[A-Z][a-z]\+, \+[0-9]\+,\? \+[A-Z][a-z]\+,\? \+[0-9]\+#\1$(SOURCE_DATE)#g' \
 	    -e 's#\(Time:.*\)[0-9][0-9]:[0-9][0-9]:[0-9][0-9]#\1$(SOURCE_TIME)#g' $${html} ; \
 	done
